Page "general" is open
"GET /app_01/main/ HTTP/1.1" 200 341
Page "about" is open
"GET /app_01/about/ HTTP/1.1" 200 264

Watching for file changes with StatReloader
C:\WORK\GB_Django\myproject\app_02\forms.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2327
Not Found: /app_02
"GET /app_02 HTTP/1.1" 404 2312
Not Found: /app_02/
"GET /app_02/ HTTP/1.1" 404 3976
Not Found: /app_02/admin
"GET /app_02/admin HTTP/1.1" 404 3991
Not Found: /app_02/admin/
"GET /app_02/admin/ HTTP/1.1" 404 3994
Internal Server Error: /app_02/customers/
Traceback (most recent call last):
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\myproject\app_02\views.py", line 29, in customer_list
    return render(request, 'myapp/customer_list.html', {'customers': customers})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/customer_list.html
"GET /app_02/customers/ HTTP/1.1" 500 79828
C:\WORK\GB_Django\myproject\app_02\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /app_02/customers/
Traceback (most recent call last):
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\myproject\app_02\views.py", line 29, in customer_list
    return render(request, 'app_02/customer_list.html', {'customers': customers})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: app_02/customer_list.html
"GET /app_02/customers/ HTTP/1.1" 500 79983
C:\WORK\GB_Django\myproject\app_02\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2327
Not Found: /app_02/
"GET /app_02/ HTTP/1.1" 404 3976
Not Found: /app_02/cusomers/
"GET /app_02/cusomers/ HTTP/1.1" 404 4003
"GET /app_02/customers/ HTTP/1.1" 200 148
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2327
"GET /app_02/customers/ HTTP/1.1" 200 148
Not Found: /app_02/product/
"GET /app_02/product/ HTTP/1.1" 404 4264
Internal Server Error: /app_02/products/
Traceback (most recent call last):
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\myproject\app_02\views.py", line 38, in product_list
    return render(request, 'app_02/product_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: app_02/product_list.html
"GET /app_02/products/ HTTP/1.1" 500 80184
"GET /app_02/product/create/ HTTP/1.1" 200 1116
"POST /app_02/product/create/ HTTP/1.1" 302 0
Internal Server Error: /app_02/products/
Traceback (most recent call last):
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\myproject\app_02\views.py", line 38, in product_list
    return render(request, 'app_02/product_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: app_02/product_list.html
"GET /app_02/products/ HTTP/1.1" 500 80674
Watching for file changes with StatReloader
"GET /app_02/products/ HTTP/1.1" 200 193
C:\WORK\GB_Django\myproject\app_02\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2327
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/css/base.css HTTP/1.1" 200 21207
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 7430
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/app_02/customer/ HTTP/1.1" 200 8442
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/core.js HTTP/1.1" 200 5682
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/app_02/order/ HTTP/1.1" 200 8421
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/product/ HTTP/1.1" 200 9722
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/product/1/change/ HTTP/1.1" 200 12514
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/css/forms.css HTTP/1.1" 200 9047
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /admin/app_02/customer/ HTTP/1.1" 200 8442
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/order/ HTTP/1.1" 200 8421
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/product/ HTTP/1.1" 200 9722
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/auth/group/ HTTP/1.1" 200 8797
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /admin/auth/user/ HTTP/1.1" 200 12460
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/app_02/customer/ HTTP/1.1" 200 8442
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/order/ HTTP/1.1" 200 8421
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/product/ HTTP/1.1" 200 9722
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/order/ HTTP/1.1" 200 8421
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\WORK\GB_Django\myproject\app_02\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\WORK\GB_Django\myproject\app_02\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\WORK\GB_Django\myproject\app_02\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/app_02/order/ HTTP/1.1" 200 9553
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/customer/ HTTP/1.1" 200 9604
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/order/ HTTP/1.1" 200 9553
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/product/ HTTP/1.1" 200 11388
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
Internal Server Error: /admin/app_02/product/1/change/
Traceback (most recent call last):
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\forms\models.py", line 300, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\forms\models.py", line 198, in fields_for_model
    raise FieldError(
django.core.exceptions.FieldError: 'addition_date' cannot be specified for Product model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
                ^^^^^^^^^^^^^^
  File "C:\WORK\GB_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: 'addition_date' cannot be specified for Product model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class ProductAdmin.
"GET /admin/app_02/product/1/change/ HTTP/1.1" 500 138380
C:\WORK\GB_Django\myproject\app_02\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/app_02/product/ HTTP/1.1" 200 11388
"GET /admin/app_02/product/ HTTP/1.1" 200 11388
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/product/1/change/ HTTP/1.1" 200 13085
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/app_02/product/ HTTP/1.1" 200 11388
